config/routes.rb
Leaderboard::Application.routes.draw do
  get "user_rankings/update"

  root to: 'staticPages#home'

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get '/users/:id', to: 'users#show', as: :user_show

  resources :rankings

  resources :user_rankings do
    member do
      put 'addpoint'
      put 'removepoint'
    end
  end

end

app/models/ranking.rb
# == Schema Information
#
# Table name: rankings
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ranking < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :user_rankings
  has_many :users, through: :user_rankings

  validates :description, presence: true
  validates :name, presence: true

  # no spaces
  VALID_NAME_REGEX =  /^[a-zA-Z0-9-_]+$/


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :user_rankings
  has_many :rankings, through: :user_rankings
end

app/models/user_ranking.rb
# == Schema Information
#
# Table name: user_rankings
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  ranking_id :integer
#  points     :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  admin      :boolean          default(FALSE)
#

class UserRanking < ActiveRecord::Base
  attr_accessible :ranking_id, :user_id, :points, :admin

  belongs_to :user
  belongs_to :ranking

  validates :user_id, presence: true
  validates :ranking_id, presence: true
  validates :points, presence: true
  validates :admin, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def new
    @ranking = Ranking.new
  end

  def create
    @ranking = Ranking.new(params[:ranking])
    if @ranking.save
      current_user.user_rankings.build(ranking_id: @ranking.id, admin: true)
      current_user.save!
      flash[:success] = "New group created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @ranking = Ranking.find(params[:id])
    #@user_rankings = @ranking.user_rankings.order('points DESC').all
    @title = @ranking.name
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @user = current_user
      @user_rankings = @user.user_rankings.all
      @title = @user.email
    end
  end
end

app/controllers/user_rankings_controller.rb
class UserRankingsController < ApplicationController
  before_filter :authenticate_user!

  def addpoint
    @user_ranking = UserRanking.find(params[:id])
    @user_ranking.update_attribute :points, @user_ranking.points + 1
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def removepoint
    @user_ranking = UserRanking.find(params[:id])
    @user_ranking.update_attribute :points, @user_ranking.points - 1
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_rankings = @user.user_rankings.all
    @title = @user.email
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_rankings_helper.rb
module UserRankingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class:"gravatar")
  end
end

app/views/layouts/_account_header.html.erb
<ul class="right">
  <li class="divider"></li>
  <% if user_signed_in? %>
    <li class="">
      <%= link_to current_user.email, user_show_path(current_user) %>
    </li>
    <li class="divider"></li>
    <li class="">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </li>  
  <% else %>
    <li class="">
    <%= link_to 'Login', new_user_session_path %>
    </li>
    <li class="divider"></li>
    <li class="">
      <%= link_to 'Register', new_user_registration_path %>
    </li> 
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<header class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to 'Leaderboard', root_path %>
      </h1>
    </li>
  </ul>

  <nav class="top-bar-section">
    <% if user_signed_in? %>
      <%= render 'layouts/user_header' %>
    <% end %>
    <%= render 'layouts/account_header' %>
  </nav>
</header>

app/views/layouts/_user_header.html.erb
<ul class="left">
  <li class="divider"></li>
  <li class="">
    <a href="">Profile</a>
  </li>
  <li class="divider"></li>
  <li class="has-dropdown">
    <a href="">Leaderboards</a>
    <ul class="dropdown">
      <% current_user.user_rankings.each do |ranking|%>
        <li><%= link_to ranking.ranking.name, ranking.ranking %></li>
      <% end %>
      <li><%= link_to 'Create Leaderboard', new_ranking_path %></li>
    </ul>
  </li>
  <li class="divider"></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>Leaderboard | <%= content_for?(:title) ? yield(:title) : "Leaderboard" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/rankings/new.html.erb
<%= form_for(@ranking, url: rankings_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true %>

    <%= f.label :description %>
    <%= f.text_area :description, required: true %>

    <%= f.submit "Create" %>
<% end %>

app/views/rankings/show.html.erb
<% provide(:title, @title) %>
<div class="row">
  <header>
    <h1><%= @ranking.name %></h1>
    <p><%= @ranking.description %></p>
    <p>
      Admins: <br />
      <% @ranking.user_rankings.each do |user_ranking|  %>
        <% if user_ranking.admin? %>
          <%= user_ranking.user.email %>
        <% end %>
      <% end %>
    </p>
  </header>
  <section>
    <ul>
      <% @ranking.user_rankings.each do |user_ranking| %>
        <li>
          <%= user_ranking.user.email %> == <span id="points"><%= user_ranking.points %></span>
          <% if user_ranking.admin? %>
            <%= link_to 'Add point', addpoint_user_ranking_path, method: :put, remote: true %>
            | <%= link_to 'Remove point', removepoint_user_ranking_path, method: :put, remote: true %>
          <% end %>
        </li>
      <% end %>
    </ul>

  </section>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_user_info.html.erb
<% provide(:title, @title) %>
<div class="row">
  <section class="small-4 columns user-info">
    <header class="centered user-info-header">
      <a href="">
        <%= gravatar_for @user, size: 100 %>
      </a>

      <h2 class="user-title">
        <%= @user.email %>
      </h2>
    </header>

  </section>

  <section class="small-8 columns">
    <section class="user-feed">
      <h2>Current Points</h2>
      <div class="rankings">
        <ul>
          <% if @user_rankings.any? %>
              <% @user_rankings.each do |ranking| %>
                  <li>
                    <%= link_to ranking.ranking.name, ranking.ranking %> | <%= ranking.points %> points
                  </li>
              <% end %>
          <% else %>
              <li>Not part of any leaderboards</li>
          <% end %>

        </ul>

      </div>
    </section>
  </section>
</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <%= render 'shared/user_info' %>
<% else %>

<h1>Leaderboard</h1>
<p>
  This is the tour page for non-signed in users
</p>

<% end %>

app/views/user_rankings/addpoint.js.erb
$("#points").html("<%= @user_ranking.points %>")

app/views/user_rankings/removepoint.js.erb
$("#points").html("<%= @user_ranking.points %>")

app/views/user_rankings/update.html.erb
<h1>UserRankings#update</h1>
<p>Find me in app/views/user_rankings/update.html.erb</p>

app/views/users/show.html.erb
<%= render 'shared/user_info' %>